apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- allowedrepos
- automount-serviceaccount-token
- block-endpoint-edit-default-role
- block-loadbalancer-services
- block-nodeport-services
- block-wildcard-ingress
- containerlimits
- containerrequests
- containerresourceratios
- disallowanonymous
- disallowedtags
- externalip
- httpsonly
- imagedigests
- noupdateserviceaccount
- poddisruptionbudget
- replicalimits
- requiredannotations
- requiredlabels
- requiredprobes
- uniqueingresshost
- uniqueserviceselector
- containerresources
- storageclass
